export const electronicsProducts = [
  {
    productImage: "https://source.unsplash.com/featured/?smartphone",
    isNew: true,
    discount: 25,
    title: "Smartphone",
    price: 799,
    discountedPrice: 599,
  },
  {
    productImage: "https://source.unsplash.com/featured/?laptop",
    isNew: false,
    discount: 15,
    title: "Laptop",
    price: 1299,
    discountedPrice: 1104,
  },
  {
    productImage: "https://source.unsplash.com/featured/?headphones",
    isNew: true,
    discount: 20,
    title: "Wireless Headphones",
    price: 199,
    discountedPrice: 159,
  },
  {
    productImage: "https://source.unsplash.com/featured/?smartwatch",
    isNew: false,
    discount: 10,
    title: "Smartwatch",
    price: 249,
    discountedPrice: 224,
  },
  {
    productImage: "https://source.unsplash.com/featured/?camera",
    isNew: true,
    discount: 30,
    title: "Mirrorless Camera",
    price: 999,
    discountedPrice: 699,
  },
  {
    productImage: "https://source.unsplash.com/featured/?tablet",
    isNew: true,
    discount: 18,
    title: "Tablet",
    price: 449,
    discountedPrice: 369,
  },
  {
    productImage: "https://source.unsplash.com/featured/?printer",
    isNew: false,
    discount: 12,
    title: "Wireless Printer",
    price: 149,
    discountedPrice: 131,
  },
  {
    productImage: "https://source.unsplash.com/featured/?gaming-laptop",
    isNew: true,
    discount: 22,
    title: "Gaming Laptop",
    price: 1899,
    discountedPrice: 1479,
  },
];
